name: Build Easy Access

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch: # Umožní manuální spuštění

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create credentials file (dummy for build)
      run: |
        echo '{"installed":{"client_id":"dummy","client_secret":"dummy","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","redirect_uris":["http://localhost"]}}' > credentials.json
      shell: bash
      
    - name: Build Vite
      run: npm run build:vite
      
    - name: Build Electron for macOS
      if: matrix.os == 'macos-latest'
      run: npm run build:mac
      
    - name: Build Electron for Windows
      if: matrix.os == 'windows-latest'
      run: npm run build:win
      
    - name: Build Electron for Linux
      if: matrix.os == 'ubuntu-latest'
      run: npm run build:linux
      
    - name: Upload macOS artifacts
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: easy-access-macos
        path: |
          dist/electron/*.dmg
          dist/electron/*.dmg.blockmap
          
    - name: Upload Windows artifacts
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: easy-access-windows
        path: |
          dist/electron/*.exe
          dist/electron/*.zip
          dist/electron/*.nsis
          
    - name: Upload Linux artifacts
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: easy-access-linux
        path: |
          dist/electron/*.AppImage
          dist/electron/*.deb
          dist/electron/*.rpm
